### PR TITLE
Multiple optimizations for performance

### PR DESCRIPTION
**Pull request by jobobby04**
- **[Add Immutable annotation to UI models](https://github.com/shosetsuorg/shosetsu/commit/86fd6559ea4d13d0b365b418255bb028fd773052)**. Its for describing that the model wont change to the compose compiler, making it generate more optimized code. For this I replaced all var variables with val to guarantee this.
- **[Add UIUpdates UI model for pre-calculated time display](https://github.com/shosetsuorg/shosetsu/commit/9550f49d5cb9530c80441bb6bb02ed04854caf1f)** This allows for the time string to be calculated outside the UI thread, since string formatting is expensive.
- **[Found a extra ComposeView lol](https://github.com/shosetsuorg/shosetsu/commit/891575f2a37f6e8a4613a2c2ddf5c1861a291ee9)**
- **[Use Empty collections where possible](https://github.com/shosetsuorg/shosetsu/commit/f266305953acb1b17af73f09eda91434245e1cfb)** I was seeing a lot of empty collections being made and each of those while dont take much space, have a location in memory. Using the empty collection functions removes those extra allocations.
- **[Improve performance of chapter lists](https://github.com/shosetsuorg/shosetsu/commit/57a3e0bab50dc7f303b79be1950530432e987fef)** by using pre-calculated values for the same reason I added the UI models.
- **[Dont remember derivedStateOf](https://github.com/shosetsuorg/shosetsu/commit/ac30b4929c8aa50a3cd4b9474069ef1440fba311)** derivedStateOf needs to watch values outside the remember function, remembering a derivedStateOf only works if it can directly access the mutableStateOf of the variables
- [**Set MutableStateFlow.value instead of .emit**](https://github.com/shosetsuorg/shosetsu/commit/124ddaae243b95ba9d34ee8bffb9f09ed062d99d) MutableStateFlow is made for watching a state of a value, if you set .value it will first check if its equal to the last value and only emit the new value if its not(since it always emits the latest value on collect, and .emit doesnt set the value, it can emit a old value by accident). You shouldn't use .emit or .tryEmit on a MutableStateFlow, if you need a flow where you can emit independent of the previous value, while keeping track of the last value, you should be using a MutableSharedFlow with a replay value of 1.

### CODE REVIEW

**Comment by jobobby04** [comment]
It might also be worth changing the Flow<> declorations in the abstract ViewModels to StateFlow<> so that you can use the collectAsState without requiring a default value, should I go ahead and do this?

**Comment by Doomsdayrs** [comment]
milk-and-mocha-cute

Someone actually made work on my app???

Oki doki, I'll be looking this over

**Review by Doomsdayrs — APPROVED** [review]
I am going to first test all effected components to make sure all things work well

**Comment by Doomsdayrs** [comment]
> It might also be worth changing the Flow<> declorations in the abstract ViewModels to StateFlow<> so that you can use the collectAsState without requiring a default value, should I go ahead and do this?

I do not think that works since many flows are directly from the database etc, only a few specific ones may benefit from such. And the effort doesn't seem worth it? Unless there is some improvement to be gained?

**Comment by jobobby04** [comment]
I meant only for those that are a MutableStareFlow in the implementations.
The main benefits would that there would be no intermediary value that is present before the flow is collected as a state, it would be the same value.
It would also allow you to check or use the value outside of the vm, like for setting the search to the current value without using a runBlocking like I have seen in some code.

**Comment by Doomsdayrs** [comment]
> I meant only for those that are a MutableStareFlow in the implementations. The main benefits would that there would be no intermediary value that is present before the flow is collected as a state, it would be the same value. It would also allow you to check or use the value outside of the vm, like for setting the search to the current value without using a runBlocking like I have seen in some code.

Honestly on the fence for this, I say leave that for a future pr. For now I shall merge this.

**Pull request merged**
